/* boltzmann_save_state.c
*******************************************************************************
boltzmann

Pacific Northwest National Laboratory, Richland, WA 99352.

Copyright (c) 2010 Battelle Memorial Institute.

Publications based on work performed using the software should include 
the following citation as a reference:


Licensed under the Educational Community License, Version 2.0 (the "License"); 
you may not use this file except in compliance with the License. 
The terms and conditions of the License may be found in 
ECL-2.0_LICENSE_TERMS.TXT in the directory containing this file.
        
Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
CONDITIONS OF ANY KIND, either express or implied. See the License for the 
specific language governing permissions and limitations under the License.
******************************************************************************/
#include "boltzmann_structs.h"
#include "boltzmann_build_agent_data_block.h"
#include "boltzmann_flatten_state.h"
#include "boltzmann_save_state.h"
int boltzmann_save_state(struct state_struct *state, 
			 void **flattened_state_p, void **agent_data_p) {
  /*
    Save a state struct generated by boltzmann_init into a contiguous
    piece of memory (for biocellion interface).
    Called by: biocellion/user, boltzmann_test_save_load
    Calls:     boltzman_save_agent_data, boltzmann_flatten_state, calloc
  */
  struct state_struct *in_state;
  void *flattened_state;
  int direction;
  int success;
  FILE *lfp;
  FILE *efp;
  in_state        = state;
  direction       = 0;
  flattened_state = NULL;
  lfp             = state->lfp;
  success = boltzmann_build_agent_data_block(state,agent_data_p);
  if (success) {
    success = boltzmann_flatten_state(&in_state,&flattened_state,direction,lfp);
  }
  *flattened_state_p = flattened_state;
  return(success);
}
  
