CC      = gcc
CLINKER = gcc
AR = ar
ARFLAGS = -crv
OPT_FLAGS = -g -O2
#
### End User configurable options ###
LIBS = libboltzmann.a -lm 
EXECS = boltzmann boltzmann_boot_test
DBG_FLAGS = -O0 -g
NO_OPT_FLAGS = -O0 -g
CFLAGS = ${OPT_FLAGS}
DCFLAGS = ${CFLAGS}
TFLAGS  =
LFLAGS = -g
default: $(EXECS)
all:  $(EXECS)
include Makefile.timing
