#ifndef _LAPAPCK_H_
#define _LAPAPCK_H_ 1
#include "blas.h"
#include "dtrsm.h"
#include "dlaswp.h"
#include "dgetrf2.h"
#include "dgetrf.h"
#include "dgetrs.h"
#include "dgbtf2.h"
#include "dgbtrs.h"
#include "dtbsv.h"
#include "dger.h"
/*
#include "dlamch.h"
#include "iladlr.h"
#include "iladlc.h"
#include "dlapy2.h"
#include "dlarfg.h"
#include "dlarf.h"
#include "dgeqr2.h"
#include "dlarft.h"
#include "dlarfb_cfl.h"
#include "dlarfb_cfr.h"
#include "dlarfb_cbl.h"
#include "dlarfb_cbr.h"
#include "dlarfb_rfl.h"
#include "dlarfb_rfr.h"
#include "dlarfb_rbl.h"
#include "dlarfb_rbr.h"
#include "dlarfb.h"
#include "dgeqrf.h"
*/
#endif
